//
//  Model.swift
//  vino
//
//  Created by Jon Grimes on 12/19/23.
//

import Foundation
import CoreLocation
//public user declaration

class Model: ObservableObject {
    @Published var activeUser = UserObj()
    @Published var userDoesntExist = true
    @Published var vineyards: [Vineyard] = [
        Vineyard("Jordan", CLLocation(latitude: 38.6562, longitude: 122.8438), "https://www.jordanwinery.com/"),
        Vineyard("Ferrari-Corrano", CLLocation(latitude: 38.7114, longitude: 122.9783), "https://www.ferrari-carano.com/"),
        Vineyard("Sanlorenzo di Ciolfi Luciano", CLLocation(latitude: 43.0436, longitude: 11.4574), "https://sanlorenzomontalcino.it/en/"),
    ]
    
    @Published var pairings: [Pairing] = []
    
    let redWines = [
        "Merlot", "Cabernet Sauvignon", "Pinot Noir", "Malbec", "Syrah",
        "Zinfandel", "Shiraz", "Cabernet Franc", "Grenache", "Tempranillo",
        "Sangiovese", "Nebbiolo", "Barbera", "Côtes du Rhône", "Rioja",
        "Chianti", "Petite Sirah", "Carménère", "Mourvèdre", "Gamay",
        "Garnacha", "Aglianico", "Tannat", "Bonarda", "Montepulciano",
        "Dolcetto", "Primitivo", "Touriga Nacional", "Corvina", "Cabernet",
        "Cabernet-Merlot", "Meritage", "Cabernet Franc", "Cabernet Blend",
        "Red Blend", "Merlot Blend", "Pinot Noir Blend", "Syrah Blend",
        "Grenache Blend", "Tempranillo Blend", "Sangiovese Blend", "Nebbiolo Blend",
        "Malbec Blend", "Carménère Blend", "Zinfandel Blend", "Shiraz Blend",
        "Petite Sirah Blend", "Mourvèdre Blend", "Gamay Blend", "Garnacha Blend",
        "Aglianico Blend", "Tannat Blend", "Bonarda Blend", "Montepulciano Blend",
        "Dolcetto Blend", "Primitivo Blend", "Touriga Nacional Blend", "Corvina Blend",
        "Cabernet Sauvignon Blend", "Merlot-Cabernet", "Cabernet-Merlot Blend",
        "Meritage Blend", "Cabernet Franc Blend", "Cabernet Blend", "Red Wine",
        "Merlot Wine", "Pinot Noir Wine", "Syrah Wine", "Grenache Wine",
        "Tempranillo Wine", "Sangiovese Wine", "Nebbiolo Wine"
    ]

    let whiteWines = [
        "Chardonnay", "Sauvignon Blanc", "Riesling", "Pinot Grigio", "Chenin Blanc",
        "Viognier", "Gewürztraminer", "Semillon", "Albariño", "Vermentino",
        "Muscat", "Gruner Veltliner", "Torrontés", "Verdejo", "Moscato",
        "Trebbiano", "White Blend", "Chardonnay Blend", "Sauvignon Blanc Blend",
        "Riesling Blend", "Pinot Grigio Blend", "Chenin Blanc Blend", "Viognier Blend",
        "Gewürztraminer Blend", "Semillon Blend", "Albariño Blend", "Vermentino Blend",
        "Muscat Blend", "Gruner Veltliner Blend", "Torrontés Blend", "Verdejo Blend",
        "Moscato Blend", "Trebbiano Blend", "Chardonnay Wine", "Sauvignon Blanc Wine",
        "Riesling Wine", "Pinot Grigio Wine", "Chenin Blanc Wine", "Viognier Wine",
        "Gewürztraminer Wine", "Semillon Wine", "Albariño Wine", "Vermentino Wine",
        "Muscat Wine", "Gruner Veltliner Wine", "Torrontés Wine", "Verdejo Wine",
        "Moscato Wine", "Trebbiano Wine", "White Wine", "Chardonnay Grape",
        "Sauvignon Blanc Grape", "Riesling Grape", "Pinot Grigio Grape", "Chenin Blanc Grape",
        "Viognier Grape", "Gewürztraminer Grape", "Semillon Grape", "Albariño Grape",
        "Vermentino Grape", "Muscat Grape", "Gruner Veltliner Grape", "Torrontés Grape",
        "Verdejo Grape", "Moscato Grape", "Trebbiano Grape", "Chardonnay Grape Variety",
        "Sauvignon Blanc Grape Variety", "Riesling Grape Variety", "Pinot Grigio Grape Variety",
        "Chenin Blanc Grape Variety", "Viognier Grape Variety", "Gewürztraminer Grape Variety"
    ]


    
    let wineDescriptors = [
        "Crisp",
        "Velvety",
        "Smooth",
        "Rich",
        "Luscious",
        "Zesty",
        "Fruity",
        "Spicy",
        "Bold",
        "Light",
        "Full-bodied",
        "Elegant",
        "Juicy",
        "Silky",
        "Aromatic",
        "Robust",
        "Complex",
        "Mellow",
        "Bright",
        "Creamy",
        "Tangy",
        "Opulent",
        "Seductive",
        "Savory",
        "Structured",
        "Balanced",
        "Fresh",
        "Floral",
        "Ripe",
        "Mineral",
        "Exotic",
        "Cedar",
        "Citrusy",
        "Buttery",
        "Earthy",
        "Charming",
        "Harmonious",
        "Crisp",
        "Voluptuous",
        "Smoky",
        "Chocolaty",
        "Intense",
        "Toasty",
        "Sparkling",
        "Vibrant",
        "Rustic",
        "Honeyed",
        "Succulent",
        "Peppery",
        "Zingy",
        "Velvet",
        "Plush",
        "Tart",
        "Austere",
        "Textured",
        "Fresh-cut",
        "Crunchy",
        "Piquant",
        "Resinous",
        "Pungent",
        "Radiant",
        "Tender",
        "Flinty",
        "Quaffable",
        "Mature",
        "Peachy",
        "Tropical",
        "Sensual",
        "Minty",
        "Brilliant",
        "Hedonistic",
        "Supple",
        "Harmonic",
        "Racy",
        "Satiny",
        "Majestic",
        "Glossy",
        "Crystalline",
        "Vivid",
        "Ebullient",
        "Intriguing",
        "Bountiful",
        "Unctuous",
        "Svelte",
        "Resplendent",
        "Wholesome",
        "Dazzling",
        "Pulsating",
        "Captivating",
        "Grandiose",
        "Quintessential",
        "Magnetic",
        "Ephemeral",
        "Pristine",
        "Mythic",
        "Eclipsing",
        "Regal",
        "Blackberry",
        "Raspberry",
        "Cherry",
        "Strawberry",
        "Plum",
        "Blueberry",
        "Currant",
        "Blackcurrant",
        "Cranberry",
        "Boysenberry",
        "Fig",
        "Date",
        "Prune",
        "Raisin",
        "Apple",
        "Pear",
        "Quince",
        "Peach",
        "Apricot",
        "Nectarine",
        "Plum",
        "Banana",
        "Pineapple",
        "Mango",
        "Melon",
        "Citrus",
        "Lemon",
        "Lime",
        "Grapefruit",
        "Orange",
        "Tangerine",
        "Mandarin",
        "Pomegranate",
        "Black Pepper",
        "White Pepper",
        "Pink Pepper",
        "Green Pepper",
        "Bell Pepper",
        "Jalapeño",
        "Anise",
        "Licorice",
        "Mint",
        "Eucalyptus",
        "Basil",
        "Rosemary",
        "Thyme",
        "Sage",
        "Lavender",
        "Violet",
        "Rose",
        "Jasmine",
        "Honeysuckle",
        "Acacia",
        "Chamomile",
        "Orange Blossom",
        "Lemon Peel",
        "Lemon Zest",
        "Grapefruit Peel",
        "Grapefruit Zest",
        "Orange Peel",
        "Orange Zest",
        "Tangerine Peel",
        "Tangerine Zest",
        "Vanilla",
        "Cinnamon",
        "Clove",
        "Nutmeg",
        "Ginger",
        "Caramel",
        "Butterscotch",
        "Toffee",
        "Chocolate",
        "Coffee",
        "Espresso",
        "Tobacco",
        "Leather",
        "Truffle",
        "Mushroom",
        "Earth",
        "Wet Leaves",
        "Graphite",
        "Slate",
        "Petrichor",
        "Smoke",
        "Tar",
        "Oak",
        "Cedar",
        "Pine",
        "Herbal",
        "Vegetal",
        "Floral",
        "Fruity",
        "Spicy",
        "Woody",
        "Nutty",
        "Savory",
        "Mineral"
    ]
}

let wineTypes = [
    "Rosé",
    "Chardonnay",
    "Cabernet Sauvignon",
    "Chianti",
    "Merlot",
    "Pinot Noir",
    "Sauvignon Blanc",
    "Syrah",
    "Zinfandel",
    "Malbec",
    "Riesling",
    "Grenache",
    "Tempranillo",
    "Sangiovese",
    "Viognier",
    "Champagne",
    "Prosecco",
    "Port Wine",
    "Shiraz",
    "Muscat",
    "Gewürztraminer",
    "Barbera",
    "Carmenere",
    "Petit Verdot",
    "Moscato",
    "Pinot Grigio",
    "Nebbiolo",
    "Albariño",
    "Vermentino",
    "Gruner Veltliner",
    "Cabernet Franc",
    "Mourvèdre",
    "Chenin Blanc",
    "Grenache Blanc",
    "Gamay",
    "Semillon",
    "Sémillon-Sauvignon Blanc blend",
    "Petite Sirah",
    "Viura"
]

let wineFlavors = [
    "Blackberry",
    "Raspberry",
    "Cherry",
    "Strawberry",
    "Plum",
    "Blueberry",
    "Currant",
    "Blackcurrant",
    "Cranberry",
    "Boysenberry",
    "Fig",
    "Date",
    "Prune",
    "Raisin",
    "Apple",
    "Pear",
    "Quince",
    "Peach",
    "Apricot",
    "Nectarine",
    "Plum",
    "Banana",
    "Pineapple",
    "Mango",
    "Melon",
    "Citrus",
    "Lemon",
    "Lime",
    "Grapefruit",
    "Orange",
    "Tangerine",
    "Mandarin",
    "Pomegranate",
    "Black Pepper",
    "White Pepper",
    "Pink Pepper",
    "Green Pepper",
    "Bell Pepper",
    "Jalapeño",
    "Anise",
    "Licorice",
    "Mint",
    "Eucalyptus",
    "Basil",
    "Rosemary",
    "Thyme",
    "Sage",
    "Lavender",
    "Violet",
    "Rose",
    "Jasmine",
    "Honeysuckle",
    "Acacia",
    "Chamomile",
    "Orange Blossom",
    "Lemon Peel",
    "Lemon Zest",
    "Grapefruit Peel",
    "Grapefruit Zest",
    "Orange Peel",
    "Orange Zest",
    "Tangerine Peel",
    "Tangerine Zest",
    "Vanilla",
    "Cinnamon",
    "Clove",
    "Nutmeg",
    "Ginger",
    "Caramel",
    "Butterscotch",
    "Toffee",
    "Chocolate",
    "Coffee",
    "Espresso",
    "Tobacco",
    "Leather",
    "Truffle",
    "Mushroom",
    "Earth",
    "Wet Leaves",
    "Graphite",
    "Slate",
    "Petrichor",
    "Smoke",
    "Tar",
    "Oak",
    "Cedar",
    "Pine",
    "Herbal",
    "Vegetal",
    "Floral",
    "Fruity",
    "Spicy",
    "Woody",
    "Nutty",
    "Savory",
    "Mineral"
]

let foodDescriptors = [
    "Savory",
    "Spicy",
    "Zesty",
    "Creamy",
    "Crunchy",
    "Tender",
    "Flavorful",
    "Hearty",
    "Luscious",
    "Juicy",
    "Succulent",
    "Crispy",
    "Smokey",
    "Satisfying",
    "Melt-in-your-mouth",
    "Robust",
    "Savory",
    "Rich",
    "Delicate",
    "Wholesome",
    "Gourmet",
    "Mouthwatering",
    "Tangy",
    "Sweet and savory",
    "Umami",
    "Exquisite",
    "Tasty",
    "Aromatic",
    "Fresh",
    "Homestyle",
    "Bold",
    "Mild",
    "Sizzling",
    "Flame-grilled",
    "Zingy",
    "Sensational",
    "Divine",
    "Exotic",
    "Fragrant",
    "Balanced",
    "Spirited",
    "Saucy",
    "Picante",
    "Mellow",
    "Sizzling",
    "Cheesy",
    "Citrusy",
    "Buttery",
    "Fruity",
    "Wholesome",
    "Mouthwatering",
    "Flaky",
    "Mouthwatering",
    "Refreshing",
    "Smoky",
    "Crunchy",
    "Silky",
    "Delectable",
    "Invigorating",
    "Bold",
    "Velvety",
    "Gratifying",
    "Honey-glazed",
    "Bountiful",
    "Piquant",
    "Velvety",
    "Crunchy",
    "Spiced",
    "Enchanting",
    "Palatable",
    "Savory-sweet",
    "Peppery",
    "Buttery",
    "Lively",
    "Caramelized",
    "Savory",
    "Flavor-packed",
    "Satisfying",
    "Scrumptious",
    "Wholesome",
    "Flavorful",
    "Fork-tender",
    "Mouthful",
    "Zesty",
    "Tantalizing",
    "Irresistible",
    "Mouth-coating",
    "Mouth-filling",
    "Mouth-puckering",
    "Mouth-stretching",
    "Mouth-gripping",
    "Mouth-drying",
    "Mouth-numbing",
    "Mouth-tingling",
    "Mouth-tingling",
    "Mouth-watering"
]

